apiVersion: apps/v1
kind: Deployment
metadata:
  name: shnootalk-playground-server
  labels:
    app: shnootalk-playground-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shnootalk-playground-server
  template:
    metadata:
      labels:
        app: shnootalk-playground-server
    spec:
      containers:
        - name: shnootalk-playground-server
          image: docker.io/shnoo28/shnootalk-playground-server:0.3.5
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 256Mi
              cpu: 500m
          env:
            - name: WORK_DIR_BASE
              value: "/work-dir/"
          volumeMounts:
            - name: work-dir
              mountPath: /work-dir/
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - >
                  curl --fail-with-body \
                    --header "Content-Type: application/json" \
                    --request POST \
                    --data '{"main.shtk": "fn main() -> int { println(\"Hello world\") return 0 }"}' \
                    http://127.0.0.1:8000/shnootalk-playground/api/v2/compile
            initialDelaySeconds: 10
            periodSeconds: 200
      volumes:
        - name: work-dir
          emptyDir:
            medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: shnootalk-playground-service
spec:
  selector:
    app: shnootalk-playground-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: shnootalk-playground-issuer
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: vishnu.vish.shankar@gmail.com
    privateKeySecretRef:
      name: shnootalk-playground-issuer
    solvers:
      - http01:
          ingress: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shnootalk-playground-ingress
  annotations:
    cert-manager.io/issuer: shnootalk-playground
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - hosts:
        - shnootalk.cc
      secretName: shnootalk-playground-certs
  rules:
    - host: shnootalk.cc
      http:
        paths:
          - path: /shnootalk-playground/api/v2
            pathType: Prefix
            backend:
              service:
                name: shnootalk-playground-service
                port:
                  number: 8000
